# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: mySkilletWT2
# label used for menu selection
label: my_skillet_label
description: INTERACT with a EDL and block

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - myCollection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: edl_name
    description: External-list name
    default: my_edl
    type_hint: text
  - name: edl_description
    description: External-list description
    default: my_edl description
    type_hint: text
  - name: edl_url
    description: External-list URL
    default: my_edl
    type_hint: url
  - name: tag_name
    description: tag name
    default: my_tag
    type_hint: text
  - name: tag_description
    description: tag description
    default: tag description
    type_hint: text
  - name: tag_color
    description: tag color
    default: red
    type_hint: dropdown
    dd_list:
      - key: green
        value: color2
      - key: orange
        value: color6
      - key: red
        value: color1

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: object_tag
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/tag
    element: |-
      <entry name="{{ tag_name }}">
        <color>{{ tag_color }}</color>
        <comments>{{ tag_description }}</comments>
      </entry>
  - name: object_external_list
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
      <external-list>
          <entry name="{{ edl_name }}">
            <type>
              <ip>
                <recurring>
                  <five-minute/>
                </recurring>
                <description>{{ edl_description }}</description>
                <url>{{ edl_url }}</url>
              </ip>
            </type>
          </entry>
        </external-list>
- name: security_rule_outbound
  xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
  element: |-
      <entry name="{{ edl_name }}-out">
        <to>
          <member>any</member>
        </to>
        <from>
          <member>any</member>
        </from>
        <source>
          <member>any</member>
        </source>
        <destination>
          <member>{{ edl_name }}</member>
        </destination>
        <source-user>
          <member>any</member>
        </source-user>
        <category>
          <member>any</member>
        </category>
        <application>
          <member>any</member>
        </application>
        <service>
          <member>application-default</member>
        </service>
        <hip-profiles>
          <member>any</member>
        </hip-profiles>
        <tag>
          <member>{{ tag_name }}</member>
        </tag>
        <action>deny</action>
        <description>outbound EDL IP block rule. EDL info: {{ edl_description }} </description>
      </entry>

- name: security_rule_inbound
  xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
  element: |-
      <entry name="{{ edl_name }}-in">
        <to>
          <member>any</member>
        </to>
        <from>
          <member>any</member>
        </from>
        <source>
          <member>{{ edl_name }}</member>
        </source>
        <destination>
          <member>any</member>
        </destination>
        <source-user>
          <member>any</member>
        </source-user>
        <category>
          <member>any</member>
        </category>
        <application>
          <member>any</member>
        </application>
        <service>
          <member>application-default</member>
        </service>
        <hip-profiles>
          <member>any</member>
        </hip-profiles>
        <tag>
          <member>{{ tag_name }}</member>
        </tag>
        <action>deny</action>
        <description>inbound EDL IP block rule. EDL info: {{ edl_description }}</description>
      </entry>

# ---------------------------------------------------------------------
# end of snippets section